collections:
  concrete5:
    output: true
    order:
      - about.md
      - prerequisites.md
      - filestructure.md
      - blankstart.md

defaults:
  - scope:
      path: ""
      type: "concrete5"
    values:
      layout: "concrete5"
    

baseurl             : "/c5tut" # does not include hostname


sass:
  style: compressed

